"""Online anomaly detector watching real-time multivariate telemetry.

Maintains a sliding persistence buffer over consecutive samples to suppress
isolated single-point sensor spikes. When Hotelling's T² or SPE/Q exceeds threshold
for N consecutive samples, an incipient ML Anomaly is declared.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone

from diagnostics.detector.model import AnomalyScore, PCAModel
from plantmind_core.telemetry import get_logger

log = get_logger("diagnostics.detector.online")


@dataclass
class AnomalyEvent:
    """An alarm-equivalent onset generated by the ML multivariate detector."""
    onset: datetime
    trigger_tag: str
    t2_ratio: float
    spe_ratio: float
    contributions: dict[str, float]
    level: str = "ML_ANOMALY"


class OnlinePCADetector:
    """Streams live telemetry samples through PCA model with a persistence filter."""

    def __init__(
        self,
        model: PCAModel,
        *,
        persistence_count: int = 3,
        window_size: int = 5,
        cooldown_s: float = 300.0,
    ):
        self._model = model
        self._persistence_count = persistence_count
        self._window_size = window_size
        self._cooldown_s = cooldown_s

        self._history: deque[AnomalyScore] = deque(maxlen=window_size)
        self._last_event_time = 0.0

    @property
    def model(self) -> PCAModel:
        return self._model

    def update_model(self, model: PCAModel) -> None:
        self._model = model
        self._history.clear()

    def process_sample(self, sample_dict: dict[str, float], ts: float | None = None) -> AnomalyEvent | None:
        """Process one live timestamped sample and evaluate persistence.

        Args:
            sample_dict: Map of tag_id -> current float value.
            ts: Epoch timestamp in seconds (defaults to current time).

        Returns:
            AnomalyEvent if persistent anomaly detected and not in cooldown, else None.
        """
        if ts is None:
            ts = datetime.now(timezone.utc).timestamp()

        score = self._model.score_sample(sample_dict, ts=ts)
        self._history.append(score)

        # Check cooldown
        if ts < (self._last_event_time + self._cooldown_s):
            return None

        # Check persistence filter: last `persistence_count` samples must all be anomalies
        if len(self._history) >= self._persistence_count:
            last_n = list(self._history)[-self._persistence_count:]
            if all(s.is_anomaly for s in last_n):
                self._last_event_time = ts
                first_breach = last_n[0]
                latest = last_n[-1]

                onset_dt = datetime.fromtimestamp(first_breach.ts, tz=timezone.utc)
                event = AnomalyEvent(
                    onset=onset_dt,
                    trigger_tag=latest.top_contributing_tag,
                    t2_ratio=round(latest.t2_ratio, 2),
                    spe_ratio=round(latest.spe_ratio, 2),
                    contributions=latest.contributions,
                    level="ML_ANOMALY",
                )
                log.warning("incipient ml anomaly detected",
                            trigger_tag=event.trigger_tag,
                            t2_ratio=event.t2_ratio, spe_ratio=event.spe_ratio,
                            onset=onset_dt.isoformat())
                return event

        return None
